[package]
name = "nexus-config-backup"
version = "0.1.3"
edition = "2021"
authors = ["Zyian"]
description = "A small utility to save all of your addons configs safely away for a rainy day."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]
name = "nexus_config_backup"

[dependencies]
walkdir = "2.4.0"
zip = "0.6.6"
dirs-next = "2.0.0"
chrono = "0.4.34"

[dependencies.nexus]
git = "https://github.com/Zerthox/nexus-rs.git"
rev = "fad2c8cfc1aa646b32d68b80858a6323375a95b8"